name: Java with Nexus Repository

on:
  workflow_dispatch:
  repository_dispatch:
    types: [doc_update]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Notify reason for workflow run
      run: echo '${{ github.event.client_payload.AUTHOR }} triggered this workflow'
    - uses: actions/checkout@v1
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Inject version number and link into pom.xml, and authentication into settings.xml
      run: |
        sed -i "s|INJECTED-VERSION|${{ vars.VERSION }}|g" pom.xml
        sed -i "s|INJECTED-DEPENDENCY|${{ github.event.client_payload.VERSION }}|g" pom.xml
        sed -i "s|http://localhost:8081|${{ vars.LINK }}|g" pom.xml
        sed -i "s|INJECTED-USERNAME|${{ secrets.USERNAME }}|g" settings.xml
        sed -i "s|INJECTED-PASSWORD|${{ secrets.PASSWORD }}|g" settings.xml
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml --settings settings.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: ${{ vars.LINK }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        format: maven2
        repository: Petclinic-Releases
        coordinates: groupId=org.springframework.samples artifactId=spring-petclinic version=${{ vars.VERSION }}
        assets: extension=jar
        filename: ./target/spring-petclinic-${{ vars.VERSION }}.jar
